version: "1"
rules:                      # Array of rules
  - base: main-for-docs            # Required. Target branch
    upstream: opensearch-project:main    # Required. Must be in the same fork network.
    mergeMethod: merge  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
  - base: main
    upstream: main        # Required. Can be a branch in the same forked repo.
    assignees:              # Optional
      - cptnb
    reviewers:              # Optional
      - cptnb
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - cptnb
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict